management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
server:
  port: ${PORT:8080}
  servlet:
    context-path: /pilatrike
spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.abumikcoduxcoviyyklz
    password: G&75*f!&+&gtRA6

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: QjVtV3oyZ0pSenN2Y0NOTE1ZYWxXbG4yVzhMbm5vWGc=